package GUI;

import Cards.Card;
import Cards.Cards;
import java.awt.Button;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;

public class Row extends javax.swing.JPanel {

    private List<Card> cards = new ArrayList<Card>();
    private List<JButton> buttons = new ArrayList<JButton>();
    
    public Row() {
        initComponents();
        Cards.init();
        addCard(Cards.getCard(1));
        addCard(Cards.getCard(2));
        addCard(Cards.getCard(0));
        System.out.println(this.cards.size());
        
        this.revalidate();
        this.repaint();
        this.doLayout();
    }
    
    public void addCard(Card card){
        this.cards.add(card);
        JButton button = new JButton();
        button.setText(card.getName());
        this.buttons.add(button);
        cardDisplay.add(button);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button)
                .addContainerGap(913, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addContainerGap())
        );
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardDisplay = new javax.swing.ButtonGroup();

        setBackground(new java.awt.Color(255, 217, 179));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setPreferredSize(new java.awt.Dimension(1000, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 996, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup cardDisplay;
    // End of variables declaration//GEN-END:variables
}
