package GUI;

import Cards.Card;
import com.sun.prism.impl.Disposer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.GridBagLayout;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JToggleButton;
/*
class Mybutton{
    Card card;
    JToggleButton button;
    
    public Mybutton(JToggleButton b, Card c){
        this.card = card;
        this.button = b;
    }
}
*/
public class RowGui extends javax.swing.JPanel {
    
    private List<Card> cards = new ArrayList<Card>();
    private List<JToggleButton> buttons = new ArrayList<JToggleButton>();
    
    //private List<Mybutton> buttons = new ArrayList<Mybutton>();

    private javax.swing.ButtonGroup cardDisplay;    
    
    public RowGui() {
        initComponents();

    }
    
    private Image getScaledImage(Image srcImg, int w, int h){
        BufferedImage resizedImg = new BufferedImage(w, h, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2 = resizedImg.createGraphics();

        g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g2.drawImage(srcImg, 0, 0, w, h, null);
        g2.dispose();

        return resizedImg;
}
    
    public void addCard(Card card){
        this.cards.add(card);
        ImageIcon image = new ImageIcon(card.getPictureLoc());
        Image resized = getScaledImage(image.getImage(), 75, 120);
        
        JToggleButton button = new JToggleButton();
        button.setText(card.getName());
        button.setMaximumSize(new Dimension(200, 300));
        button.setPreferredSize(new Dimension(90, 120));
        button.setBackground(new Color(210, 210, 210) );

        JLabel inner = new JLabel(new ImageIcon(resized),JLabel.CENTER);
        button.add(inner);
        
        this.buttons.add(button);
        cardDisplay.add(button);
        this.add(button);
       
        this.revalidate();
        this.repaint();
        this.doLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        cardDisplay = new javax.swing.ButtonGroup();

        setBackground(new java.awt.Color(255, 217, 179));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        setPreferredSize(new java.awt.Dimension(1000, 130));

        this.setLayout(new GridBagLayout());
    }                    
/*
    public Card getSelected(){
        cardDisplay.getSelection();
        return 
    }
                 
     */          
}
